-- Duplicate Worksheet Header
CREATE OR REPLACE PROCEDURE TB_2_TS.TTTM_RAW.POPULATE_WORKSHEET_HEADER2("EXEC_ID_INPUT" VARCHAR(16777216))
    RETURNS VARCHAR(16777216)
    LANGUAGE SQL EXECUTE
    AS OWNER
    AS '
BEGIN
    TRUNCATE TABLE TB_2_TS.TTTM_RAW.WORKSHEET_HEADER2;
    

    INSERT INTO TB_2_TS.TTTM_RAW.WORKSHEET_HEADER2
    SELECT * FROM TB_2_TS.TTTM_RAW.WORKSHEET_HEADER;
   

    RETURN ''SUCCESS'';
END;
';